# Generated by Django 4.1.5 on 2023-01-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
    ]
